version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8100:8080"
    networks:
      - restaurant-network
    volumes:
      - ./nacos/data:/home/nacos/data
      - ./nacos/logs:/home/nacos/logs
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -f http://localhost:8848/nacos/v1/ns/operator/servers || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  r-user-db:
    image: mysql:8
    container_name: r-user-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_user
    ports:
      - "3307:3306"
    volumes:
      - r-user-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  r-dish-db:
    image: mysql:8
    container_name: r-dish-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_dish
    ports:
      - "3308:3306"
    volumes:
      - r-dish-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  r-order-db:
    image: mysql:8
    container_name: r-order-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_order
    ports:
      - "3309:3306"
    volumes:
      - r-order-db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  r-user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    #    container_name:
    ports:
          - "8081:8081"
    environment:
      NACOS_HOST: nacos
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
      SPRING_DATASOURCE_URL: jdbc:mysql://r-user-db:3306/restaurant_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8081
    depends_on:
      r-user-db:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - restaurant-network
    restart: unless-stopped

  r-dish-service:
    build:
      context: ./dish_service
      dockerfile: Dockerfile
    #    container_name:
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://r-dish-db:3306/restaurant_dish?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8082
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
      NACOS_HOST: nacos
    depends_on:
      r-dish-db:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - restaurant-network
    restart: unless-stopped

  r-order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    #    container_name:
    ports:
      - "8083:8083"
    environment:
      NACOS_HOST: nacos
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://r-order-db:3306/restaurant_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8083
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
    depends_on:
      r-order-db:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - restaurant-network
    restart: unless-stopped
    
  r-gateway-service:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Gateway 端口
      SERVER_PORT: 8900
      # Nacos 注册 & 配置中心地址（关键）
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos:8848
      SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR: nacos:8848
      # 建议显式开启 discovery locator（避免 lb:// 不生效）
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"

    depends_on:
      nacos:
        condition: service_started
      r-user-service:
        condition: service_started
      r-dish-service:
        condition: service_started
      r-order-service:
        condition: service_started
    networks:
      - restaurant-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - restaurant-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge
#    external: true

volumes:
  r-user-db-data:
    driver: local
  r-dish-db-data:
    driver: local
  r-order-db-data:
    driver: local
  nacos-data:
    driver: local
  nacos-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

