global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['r-user-service:8081']
        labels:
          application: 'user-service'

  - job_name: 'dish-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['r-dish-service:8082']
        labels:
          application: 'dish-service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['r-order-service:8083']
        labels:
          application: 'order-service'

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['r-gateway-service:8900']
        labels:
          application: 'gateway-service'
