spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/restaurant_dish?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false


  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        group: RESTAURANT_GROUP
      discovery:
        server-addr: localhost:8848
#        namespace: public
#        group: RESTAURANT_GROUP
#        ephemeral: true
#        heart-beat-interval: 5000
#        heart-beat-timeout: 15000
        username: nacos
        password: nacos
        enabled: true